"""TAPDB Core Base Class.

Defines the abstract base class for the TAPDB core tables.

Phase 2 spec: ORM must match schema:
- TIMESTAMPTZ => DateTime(timezone=True)
- JSONB => sqlalchemy.dialects.postgresql.JSONB
- non-nullability should match schema defaults/constraints
"""

import sqlalchemy.orm as sqla_orm
from sqlalchemy import Boolean, Column, DateTime, FetchedValue, Text
from sqlalchemy.dialects.postgresql import JSONB, UUID

Base = sqla_orm.declarative_base()


class tapdb_core(Base):
    """
    Abstract base class for all TAPDB entities.

    All three tables (generic_template, generic_instance, generic_instance_lineage)
    inherit from this class. Columns use server_default for DB-owned values.

    Attributes:
        uuid: Primary key, generated by database (gen_random_uuid())
        euid: Enterprise Unique ID, generated by database trigger
        name: Human-readable display name (application-managed)
        created_dt: Creation timestamp (DB-managed)
        modified_dt: Last modification timestamp (DB-managed)
        polymorphic_discriminator: SQLAlchemy single-table inheritance discriminator
        category: Top-level category (workflow, container, content, etc.)
        type: Type within category (assay, plate, specimen, etc.)
        subtype: Specific variant (hla-typing, fixed-plate-96, etc.)
        version: Version string for templates
        bstatus: Business status (active, archived, etc.)
        json_addl: Flexible JSON storage for domain-specific data
        is_singleton: Whether only one instance can exist per template
        is_deleted: Soft delete flag (DB-managed via trigger)
    """
    __abstract__ = True

    # DB-owned identifiers
    uuid = Column(UUID, primary_key=True, nullable=False, server_default=FetchedValue())
    euid = Column(Text, nullable=False, server_default=FetchedValue())

    # Application-managed display name
    name = Column(Text, nullable=False)

    # DB-owned timestamps
    created_dt = Column(
        DateTime(timezone=True),
        nullable=False,
        server_default=FetchedValue(),
    )
    modified_dt = Column(
        DateTime(timezone=True),
        nullable=True,
        server_default=FetchedValue(),
        server_onupdate=FetchedValue(),
    )

    # Type hierarchy
    polymorphic_discriminator = Column(Text, nullable=False)
    category = Column(Text, nullable=False)
    type = Column(Text, nullable=False)
    subtype = Column(Text, nullable=False)
    version = Column(Text, nullable=False)

    # Business status
    bstatus = Column(Text, nullable=False)

    # Flexible storage (JSONB)
    json_addl = Column(
        JSONB,
        nullable=False,
        default=dict,
        server_default=FetchedValue(),
    )

    # Lifecycle flags
    is_singleton = Column(Boolean, nullable=False, server_default=FetchedValue())
    is_deleted = Column(Boolean, nullable=False, server_default=FetchedValue())

    @staticmethod
    def sort_by_euid(items: list) -> list:
        """Sort a list of TAPDB entities by their EUID."""
        return sorted(items, key=lambda x: x.euid or "")

    def __repr__(self) -> str:
        return f"<{self.__class__.__name__}(euid={self.euid!r}, name={self.name!r})>"
