"""
TAPDB Core Base Class.

Defines the abstract base class for all TAPDB entities with common columns.
All columns use server_default/server_onupdate - the database owns these values.
"""
from sqlalchemy import Column, Text, TIMESTAMP, JSON, BOOLEAN, FetchedValue
from sqlalchemy.dialects.postgresql import UUID
import sqlalchemy.orm as sqla_orm

Base = sqla_orm.declarative_base()


class tapdb_core(Base):
    """
    Abstract base class for all TAPDB entities.

    All three tables (generic_template, generic_instance, generic_instance_lineage)
    inherit from this class. Columns use server_default for DB-owned values.

    Attributes:
        uuid: Primary key, generated by database (gen_random_uuid())
        euid: Enterprise Unique ID, generated by database trigger
        name: Human-readable display name (application-managed)
        created_dt: Creation timestamp (DB-managed)
        modified_dt: Last modification timestamp (DB-managed)
        polymorphic_discriminator: SQLAlchemy single-table inheritance discriminator
        category: Top-level category (workflow, container, content, etc.)
        type: Type within category (assay, plate, specimen, etc.)
        subtype: Specific variant (hla-typing, fixed-plate-96, etc.)
        version: Version string for templates
        bstatus: Business status (active, archived, etc.)
        json_addl: Flexible JSON storage for domain-specific data
        is_singleton: Whether only one instance can exist per template
        is_deleted: Soft delete flag (DB-managed via trigger)
    """
    __abstract__ = True

    uuid = Column(UUID, primary_key=True, nullable=True, server_default=FetchedValue())
    euid = Column(Text, nullable=True, server_default=FetchedValue())
    name = Column(Text, nullable=True)

    created_dt = Column(TIMESTAMP, nullable=True, server_default=FetchedValue())
    modified_dt = Column(TIMESTAMP, nullable=True, server_default=FetchedValue())

    polymorphic_discriminator = Column(Text, nullable=True)

    category = Column(Text, nullable=True)
    type = Column(Text, nullable=True)
    subtype = Column(Text, nullable=True)
    version = Column(Text, nullable=True)

    bstatus = Column(Text, nullable=True)

    json_addl = Column(JSON, nullable=True)

    is_singleton = Column(BOOLEAN, nullable=False, server_default=FetchedValue())
    is_deleted = Column(BOOLEAN, nullable=True, server_default=FetchedValue())

    @staticmethod
    def sort_by_euid(items: list) -> list:
        """Sort a list of TAPDB entities by their EUID."""
        return sorted(items, key=lambda x: x.euid or "")

    def __repr__(self) -> str:
        return f"<{self.__class__.__name__}(euid={self.euid!r}, name={self.name!r})>"
