"""Real PostgreSQL historical-schema capture, restore and aborted allocations."""

from uuid import uuid4

import pytest
from sqlalchemy import create_engine, text
from sqlalchemy.pool import NullPool

from daylily_tapdb.backup import service, verify
from daylily_tapdb.backup.errors import BackupVerificationError
from daylily_tapdb.backup.receipts import Actor
from daylily_tapdb.backup.recovery import (
    begin_recovery,
    finish_recovery,
    retained_recovery_state,
)
from daylily_tapdb.backup.source_contract import capture_source_contract
from daylily_tapdb.cli.context import clear_cli_context, set_cli_context
from daylily_tapdb.cli.db_config import get_backup_settings, get_db_config
from daylily_tapdb.identity_inventory import (
    capture_identity_inventory,
    verify_identity_inventory,
)
from daylily_tapdb.runtime_principal import operator_session
from daylily_tapdb.sequences import (
    acquire_database_writer_fence,
    apply_sequence_advance_plan,
    build_sequence_advance_plan,
    capture_sequence_inventory,
    record_sequence_advance_outcome,
    release_database_writer_fence,
    validate_writer_fence,
)


@pytest.fixture
def historical_source(pg_instance, tmp_path):
    set_cli_context(config_path=pg_instance["config_path"])
    cfg = dict(get_db_config())
    schema = "historical_" + uuid4().hex[:12]
    cfg["schema_name"] = schema
    settings = dict(get_backup_settings())
    settings["config_dir"] = str(tmp_path)
    settings["storage_uri"] = f"file://{tmp_path / 'store'}"
    engine = create_engine(
        pg_instance["operator_dsn"], isolation_level="SERIALIZABLE", poolclass=NullPool
    )
    with engine.begin() as connection:
        connection.exec_driver_sql(f'CREATE SCHEMA "{schema}"')
        connection.exec_driver_sql(
            f'CREATE TABLE "{schema}".historical_record ('
            "uid bigint GENERATED BY DEFAULT AS IDENTITY (START WITH 1 INCREMENT BY 7) PRIMARY KEY, "
            "created_dt timestamptz NOT NULL DEFAULT current_timestamp, payload text NOT NULL)"
        )
        # Persisted identities come only from PostgreSQL's owning table.
        uid = connection.execute(
            text(
                f"INSERT INTO \"{schema}\".historical_record(payload) VALUES ('original') RETURNING uid"
            )
        ).scalar_one()
        connection.exec_driver_sql(
            f'CREATE TABLE "{schema}".historical_assertion (parent_uid bigint REFERENCES "{schema}".historical_record(uid), statement text)'
        )
        connection.execute(
            text(
                f"INSERT INTO \"{schema}\".historical_assertion VALUES (:uid, 'retained'), (:uid, 'retained')"
            ),
            {"uid": uid},
        )
    yield cfg, settings, engine
    engine.dispose()
    clear_cli_context()


def _contract(cfg, engine):
    with engine.connect() as connection, connection.begin():
        connection.execute(text("SET LOCAL TIME ZONE 'UTC'"))
        connection.execute(text(f'SET LOCAL search_path = "{cfg["schema_name"]}"'))
        return capture_source_contract(
            connection,
            schema_name=cfg["schema_name"],
            target=service.inventory_target(cfg),
            source_version="0.0.0-fixture",
        )


def test_complete_historical_schema_round_trip_requires_no_current_runtime(
    historical_source,
):
    cfg, settings, engine = historical_source
    contract = _contract(cfg, engine)
    engine.dispose()
    backup = service.create_backup(cfg, settings, source_contract=contract)
    assert backup.manifest.source_contract["source_version"] == "0.0.0-fixture"
    assert backup.manifest.row_counts["historical_assertion"] == 2
    assert backup.manifest.sequences[0].increment_by == 7
    target_db = "history_restore_" + uuid4().hex[:12]
    result = verify.restore_backup(
        cfg,
        settings,
        backup_id=backup.backup_id,
        options=verify.RestoreOptions(target_database=target_db),
        recovery_source={"purpose": "isolated_rehearsal"},
    )
    assert result.ok, result.to_payload()
    assert result.principal_binding_required
    assert (
        retained_recovery_state(
            service.receipts_directory(settings),
            target={
                **service.inventory_target(cfg),
                "database": target_db,
            },
        )["pending"]
        == {}
    )


def test_physical_snapshot_detects_duplicate_historical_assertion_loss(
    historical_source,
):
    cfg, _settings, engine = historical_source
    target = service.inventory_target(cfg)
    with engine.begin() as connection:
        before = capture_identity_inventory(
            connection, schema_name=cfg["schema_name"], target=target
        )
        connection.execute(
            text(
                f'DELETE FROM "{cfg["schema_name"]}".historical_assertion WHERE ctid=(SELECT ctid FROM "{cfg["schema_name"]}".historical_assertion LIMIT 1)'
            )
        )
        after = capture_identity_inventory(
            connection, schema_name=cfg["schema_name"], target=target
        )
        result = verify_identity_inventory(before, after)
        assert not result["ok"]
        assert any("original_row_missing" in item for item in result["violations"])


def test_aborted_database_allocation_is_retained_outside_database(
    historical_source, tmp_path
):
    cfg, _settings, engine = historical_source
    target = service.inventory_target(cfg)
    actor = Actor(surface="cli", username="test-operator")
    receipts = tmp_path / "receipts"
    engine.dispose()
    # The fixture's explicitly created control database is independent of the
    # target. Extra login administrators cannot bypass a disabled target gate.
    with (
        operator_session(
            dict(cfg, database="postgres"), isolation_level="SERIALIZABLE"
        ) as control,
        operator_session(cfg, isolation_level="SERIALIZABLE") as connection,
    ):
        with connection.begin():
            before = capture_sequence_inventory(
                connection, schema_name=cfg["schema_name"], target=target
            )
        gate = acquire_database_writer_fence(
            connection,
            control_connection=control,
            inventory=before,
            receipts_dir=receipts,
        )
        fence = gate["fence"]
        with connection.begin():
            validate_writer_fence(connection, before, fence)
            intent = begin_recovery(
                receipts,
                target=target,
                inventories=[before],
                evidence={"purpose": "fenced_migration"},
                actor=actor,
            )
        transaction = connection.begin()
        issued = connection.execute(
            text(
                f"SELECT nextval('\"{cfg['schema_name']}\".historical_record_uid_seq')"
            )
        ).scalar_one()
        transaction.rollback()
        with connection.begin():
            after = capture_sequence_inventory(
                connection, schema_name=cfg["schema_name"], target=target
            )
            validate_writer_fence(connection, after, fence)
            finish_recovery(
                receipts, intent, phase="aborted", actor=actor, inventory=after
            )
        retained = retained_recovery_state(receipts, target=target)
        assert max(item["value"] for item in retained["floors"]) == issued
        plan = build_sequence_advance_plan(after, floors=retained["floors"])
        with connection.begin():
            applied = apply_sequence_advance_plan(
                connection, plan, writer_fence=fence, receipts_dir=receipts
            )
        committed = record_sequence_advance_outcome(
            applied,
            receipts_dir=receipts,
            outcome="committed",
            actor=cfg["operator_user"],
        )
        release_database_writer_fence(
            connection,
            gate,
            result=committed,
            receipts_dir=receipts,
            control_connection=control,
        )


def test_historical_backup_rejects_stale_source_contract(historical_source):
    cfg, settings, engine = historical_source
    contract = _contract(cfg, engine)
    with engine.begin() as connection:
        connection.execute(
            text(
                f"UPDATE \"{cfg['schema_name']}\".historical_record SET payload='changed'"
            )
        )
    engine.dispose()
    with pytest.raises(BackupVerificationError, match="reviewed contract"):
        service.create_backup(cfg, settings, source_contract=contract)
