"""Exhaustive, historical-schema capture against a real PostgreSQL."""

from __future__ import annotations

from uuid import uuid4

import pytest
from sqlalchemy import create_engine, text
from sqlalchemy.exc import DBAPIError
from sqlalchemy.pool import NullPool
from typer.testing import CliRunner

import daylily_tapdb.identity_inventory as inventory_module
from daylily_tapdb.cli import app
from daylily_tapdb.identity_inventory import (
    IdentityInventoryError,
    capture_identity_inventory,
    verify_identity_inventory,
)


@pytest.fixture
def historical(pg_instance):
    schema = "historical_" + uuid4().hex
    engine = create_engine(
        pg_instance["operator_dsn"],
        poolclass=NullPool,
        isolation_level="REPEATABLE READ",
    )
    target = {
        "engine_type": "local",
        "host": "localhost",
        "port": pg_instance["port"],
        "database": pg_instance["database"],
        "schema_name": schema,
        "config_identity": str(pg_instance["config_path"]),
        "domain_code": "Z",
        "owner_repo_name": "daylily-tapdb",
    }
    with engine.begin() as connection:
        connection.execute(text(f'CREATE SCHEMA "{schema}"'))
        connection.execute(
            text(
                f'CREATE TABLE "{schema}".original_history (uid bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, parent_uid bigint REFERENCES "{schema}".original_history(uid), created_at timestamptz NOT NULL, note text, is_deleted boolean NOT NULL)'
            )
        )
        connection.execute(
            text(
                f"INSERT INTO \"{schema}\".original_history(created_at,note,is_deleted) VALUES ('2026-09-10T20:00:00Z','kept',false),('2026-09-10T20:00:01Z','deleted-but-preserved',true)"
            )
        )
        connection.execute(text(f'CREATE TABLE "{schema}".unkeyed_history(note text)'))
        connection.execute(
            text(f"INSERT INTO \"{schema}\".unkeyed_history VALUES ('same'),('same')")
        )
        # Neither table appears in the previous fixed TapDB inventory.
    yield engine, target
    with engine.begin() as connection:
        connection.execute(text(f'DROP SCHEMA "{schema}" CASCADE'))
    engine.dispose()


def capture(connection, target):
    return capture_identity_inventory(
        connection, schema_name=target["schema_name"], target=target
    )


def test_historical_capture_needs_no_tapdb_runtime_schema(historical):
    engine, target = historical
    with engine.begin() as connection:
        before = capture(connection, target)
        after = capture(connection, target)
    assert before == after
    assert set(before["tables"]) == {"original_history", "unkeyed_history"}
    history = before["tables"]["original_history"]
    assert history["row_count"] == 2
    assert {"uid", "parent_uid", "created_at"} <= set(history["immutable_columns"])
    assert len(history["constraints"]) == 2 and history["dependencies"]
    reference = next(item for item in history["constraints"] if item["kind"] == "f")
    assert reference["referenced_schema"] == target["schema_name"]
    assert reference["referenced_table"] == "original_history"
    assert reference["referenced_columns"] == ["uid"]
    assert reference["validated"] is True
    assert before["tables"]["unkeyed_history"]["rows"]
    assert (
        next(iter(before["tables"]["unkeyed_history"]["rows"].values()))["count"] == 2
    )
    assert verify_identity_inventory(before, after)["ok"]
    assert "deleted-but-preserved" not in inventory_module.canonical_json(before)


def test_removed_history_duplicate_and_unknown_table_changes_are_detected(historical):
    engine, target = historical
    with engine.begin() as connection:
        before = capture(connection, target)
        connection.execute(
            text(
                f'DELETE FROM "{target["schema_name"]}".unkeyed_history WHERE ctid IN (SELECT ctid FROM "{target["schema_name"]}".unkeyed_history LIMIT 1)'
            )
        )
        after = capture(connection, target)
        assert not verify_identity_inventory(before, after)["ok"]
        connection.execute(
            text(
                f'CREATE TABLE "{target["schema_name"]}".new_history (uid bigint PRIMARY KEY)'
            )
        )
        latest = capture(connection, target)
    assert (
        "new_history:undeclared_table_added"
        in verify_identity_inventory(after, latest)["violations"]
    )


def test_capture_requires_snapshot_and_exact_physical_target(historical):
    engine, target = historical
    with engine.connect().execution_options(
        isolation_level="READ COMMITTED"
    ) as connection:
        with (
            connection.begin(),
            pytest.raises(IdentityInventoryError, match="REPEATABLE READ"),
        ):
            capture(connection, target)
    with engine.begin() as connection:
        with pytest.raises(IdentityInventoryError, match="physical target"):
            capture(connection, dict(target, database="wrong_target"))
    with engine.begin() as connection:
        with pytest.raises(IdentityInventoryError, match="Schema does not exist"):
            capture(connection, dict(target, schema_name="not_present"))


def test_read_only_capture_rejects_incomplete_forced_rls_visibility(
    historical, pg_instance
):
    engine, target = historical
    schema = target["schema_name"]
    runtime = pg_instance["user"]
    with engine.begin() as connection:
        connection.execute(
            text(f'ALTER TABLE "{schema}".original_history ENABLE ROW LEVEL SECURITY')
        )
        connection.execute(
            text(f'ALTER TABLE "{schema}".original_history FORCE ROW LEVEL SECURITY')
        )
        connection.execute(
            text(
                f'CREATE POLICY partial ON "{schema}".original_history USING (NOT is_deleted)'
            )
        )
        connection.execute(text(f'GRANT USAGE ON SCHEMA "{schema}" TO "{runtime}"'))
        connection.execute(
            text(f'GRANT SELECT ON ALL TABLES IN SCHEMA "{schema}" TO "{runtime}"')
        )
    runtime_engine = create_engine(
        pg_instance["dsn"], poolclass=NullPool, isolation_level="REPEATABLE READ"
    )
    try:
        with (
            runtime_engine.begin() as connection,
            pytest.raises(DBAPIError, match="complete FORCE-RLS"),
        ):
            capture(connection, target)
    finally:
        runtime_engine.dispose()
    with engine.begin() as connection:
        full = capture(connection, target)
        assert full["tables"]["original_history"]["row_count"] == 2
        assert full["tables"]["original_history"]["rls_forced"]


@pytest.mark.parametrize(
    ("constant", "bound"),
    [("MAX_ROWS", 1), ("MAX_ROW_BYTES", 1), ("MAX_RECEIPT_BYTES", 1)],
)
def test_capture_content_and_receipt_bounds_fail_loudly(
    historical, monkeypatch, constant, bound
):
    engine, target = historical
    monkeypatch.setattr(inventory_module, constant, bound)
    with (
        engine.begin() as connection,
        pytest.raises(IdentityInventoryError, match="bound"),
    ):
        capture(connection, target)


def test_current_tapdb_inventory_contains_only_owner_minted_euids(pg_instance):
    runner = CliRunner()
    config = str(pg_instance["config_path"])
    result = runner.invoke(app, ["--config", config, "db", "schema", "apply"])
    assert result.exit_code == 0, result.output
    result = runner.invoke(
        app, ["--config", config, "db", "data", "seed", "--skip-existing"]
    )
    assert result.exit_code == 0, result.output
    engine = create_engine(
        pg_instance["operator_dsn"],
        poolclass=NullPool,
        isolation_level="REPEATABLE READ",
    )
    target = {
        "engine_type": "local",
        "host": "localhost",
        "port": pg_instance["port"],
        "database": pg_instance["database"],
        "schema_name": pg_instance["schema_name"],
        "config_identity": config,
        "domain_code": "Z",
        "owner_repo_name": "daylily-tapdb",
    }
    try:
        with engine.begin() as connection:
            evidence = capture(connection, target)
            templates = evidence["tables"]["generic_template"]["rows"]
            # The session-scoped database may contain other tests' legitimate
            # templates; every persisted row must still be inventoried.
            assert (
                templates
                and len(templates)
                == connection.execute(
                    text(
                        f'SELECT count(*) FROM "{target["schema_name"]}".generic_template'
                    )
                ).scalar_one()
            )
            for row in templates.values():
                identity = row["identity"]
                persisted = connection.execute(
                    text(
                        f'SELECT euid FROM "{target["schema_name"]}".generic_template WHERE uid=:uid'
                    ),
                    {"uid": identity["uid"]},
                ).scalar_one()
                assert identity["euid"] == persisted
    finally:
        engine.dispose()


def test_constrained_schema_owner_complete_force_rls_capture(historical, pg_instance):
    engine, target = historical
    schema = target["schema_name"]
    owner = "inventory_owner_" + uuid4().hex
    with engine.begin() as connection:
        connection.execute(text(f'CREATE ROLE "{owner}" LOGIN NOSUPERUSER NOBYPASSRLS'))
        connection.execute(
            text(f'GRANT CONNECT ON DATABASE "{target["database"]}" TO "{owner}"')
        )
        connection.execute(text(f'ALTER SCHEMA "{schema}" OWNER TO "{owner}"'))
        connection.execute(
            text(f'ALTER TABLE "{schema}".original_history OWNER TO "{owner}"')
        )
        connection.execute(
            text(f'ALTER TABLE "{schema}".unkeyed_history OWNER TO "{owner}"')
        )
        connection.execute(
            text(f'ALTER TABLE "{schema}".original_history ENABLE ROW LEVEL SECURITY')
        )
        connection.execute(
            text(f'ALTER TABLE "{schema}".original_history FORCE ROW LEVEL SECURITY')
        )
        connection.execute(
            text(
                f'CREATE POLICY tapdb_operator_access ON "{schema}".original_history FOR ALL TO "{owner}" USING (true) WITH CHECK (true)'
            )
        )
        expected = capture(connection, target)
    owner_engine = create_engine(
        engine.url.set(username=owner),
        poolclass=NullPool,
        isolation_level="REPEATABLE READ",
    )
    try:
        with owner_engine.begin() as connection:
            connection.execute(text("SET TRANSACTION READ ONLY"))
            actual = capture(connection, target)
            assert actual == expected
            assert actual["tables"]["original_history"]["row_count"] == 2
        with engine.begin() as connection:
            connection.execute(
                text(
                    f'CREATE POLICY hidden_deleted ON "{schema}".original_history AS RESTRICTIVE FOR SELECT TO "{owner}" USING (NOT is_deleted)'
                )
            )
        with (
            owner_engine.begin() as connection,
            pytest.raises(DBAPIError, match="complete FORCE-RLS"),
        ):
            capture(connection, target)
    finally:
        owner_engine.dispose()
        with engine.begin() as connection:
            connection.execute(
                text(f'DROP POLICY hidden_deleted ON "{schema}".original_history')
            )
            connection.execute(
                text(
                    f'DROP POLICY tapdb_operator_access ON "{schema}".original_history'
                )
            )
            connection.execute(
                text(
                    f'ALTER TABLE "{schema}".original_history OWNER TO "{pg_instance["operator_user"]}"'
                )
            )
            connection.execute(
                text(
                    f'ALTER TABLE "{schema}".unkeyed_history OWNER TO "{pg_instance["operator_user"]}"'
                )
            )
            connection.execute(
                text(
                    f'ALTER SCHEMA "{schema}" OWNER TO "{pg_instance["operator_user"]}"'
                )
            )
            connection.execute(
                text(
                    f'REVOKE CONNECT ON DATABASE "{target["database"]}" FROM "{owner}"'
                )
            )
            connection.execute(text(f'DROP ROLE "{owner}"'))


def test_capture_is_stable_across_timezone_and_search_path(historical):
    engine, target = historical
    with engine.begin() as connection:
        connection.execute(text("SET LOCAL TimeZone = 'America/New_York'"))
        connection.execute(
            text(f'SET LOCAL search_path = "{target["schema_name"]}", public')
        )
        first = capture(connection, target)
        assert (
            connection.execute(text("SELECT current_schema()")).scalar_one()
            == target["schema_name"]
        )
    with engine.begin() as connection:
        connection.execute(text("SET LOCAL TimeZone = 'Asia/Tokyo'"))
        connection.execute(text("SET LOCAL search_path = pg_catalog"))
        second = capture(connection, target)
    assert first == second
