"""Allocator safety on a real local PostgreSQL, including rollback and caches."""

from __future__ import annotations

from pathlib import Path
from uuid import uuid4

import pytest
from sqlalchemy import create_engine, text
from sqlalchemy.engine import make_url
from sqlalchemy.pool import NullPool

from daylily_tapdb.backup.receipts import read_head, read_receipts, verify_receipt_chain
from daylily_tapdb.identity_inventory import IdentityInventoryError, seal_receipt
from daylily_tapdb.sequence_fence import backend_identity
from daylily_tapdb.sequences import (
    SequenceProtectionError,
    apply_sequence_advance_plan,
    build_sequence_advance_plan,
    capture_sequence_inventory,
    record_sequence_advance_outcome,
    sequence_next_value,
    validate_writer_fence,
    verify_sequence_floors,
)


@pytest.fixture
def allocator(pg_instance):
    schema = "allocator_" + uuid4().hex
    database = "allocator_db_" + uuid4().hex
    admin = create_engine(
        pg_instance["operator_dsn"], poolclass=NullPool, isolation_level="AUTOCOMMIT"
    )
    with admin.connect() as connection:
        connection.execute(
            text(f'CREATE DATABASE "{database}" OWNER "{pg_instance["operator_user"]}"')
        )
    engine = create_engine(
        make_url(pg_instance["operator_dsn"]).set(database=database),
        poolclass=NullPool,
        isolation_level="REPEATABLE READ",
    )
    target = {
        "engine_type": "local",
        "host": "localhost",
        "port": pg_instance["port"],
        "database": database,
        "schema_name": schema,
        "config_identity": str(pg_instance["config_path"]),
        "domain_code": "Z",
        "owner_repo_name": "daylily-tapdb",
    }
    with engine.begin() as connection:
        connection.execute(text(f'CREATE SCHEMA "{schema}"'))
        connection.execute(
            text(
                f'CREATE TABLE "{schema}".objects (uid bigint GENERATED BY DEFAULT AS IDENTITY (START 2 INCREMENT 3 MINVALUE 2 MAXVALUE 101 CACHE 1) PRIMARY KEY, note text)'
            )
        )
        connection.execute(
            text(f"INSERT INTO \"{schema}\".objects (note) VALUES ('first'),('second')")
        )
        connection.execute(text(f'REVOKE CONNECT ON DATABASE "{database}" FROM PUBLIC'))
    yield engine, target
    engine.dispose()
    with admin.connect() as connection:
        connection.execute(text(f'DROP DATABASE "{database}"'))
    admin.dispose()


def capture(connection, target):
    return capture_sequence_inventory(
        connection, schema_name=target["schema_name"], target=target
    )


def fence(current):
    return {
        "mode": "exclusive_database_connect",
        "database_oid": current["physical_target"]["database_oid"],
        "operator_role": "tapdb_operator",
    }


@pytest.fixture
def control_connection(pg_instance):
    # Explicit test control DB created by initdb, never a runtime fallback.
    engine = create_engine(
        make_url(pg_instance["operator_dsn"]).set(database="postgres"),
        poolclass=NullPool,
        isolation_level="REPEATABLE READ",
    )
    try:
        with engine.connect() as connection:
            yield connection
    finally:
        engine.dispose()


def test_catalog_inventory_captures_real_identity_definition(allocator):
    engine, target = allocator
    with engine.begin() as connection:
        current = capture(connection, target)
    state = current["sequences"][0]
    assert state["name"] == "objects_uid_seq"
    assert state["increment_by"] == 3
    assert state["last_value"] == 5 and state["is_called"] is True
    assert state["assigned_floor"] == 5 and state["allocated_floor"] == 5
    assert state["mapping"]["kind"] == "owned_column"
    assert state["mapping"]["columns"][0]["dependency_type"] == "i"
    assert state["dependencies"]


def test_transactional_advance_commit_and_strict_verification(allocator, tmp_path):
    engine, target = allocator
    floors = [{"name": "objects_uid_seq", "value": 9, "source": "fenced_source"}]
    with engine.begin() as connection:
        before = capture(connection, target)
        plan = build_sequence_advance_plan(before, floors=floors)
        result = apply_sequence_advance_plan(
            connection, plan, writer_fence=fence(before), receipts_dir=tmp_path
        )
    outcome = record_sequence_advance_outcome(
        result, receipts_dir=tmp_path, outcome="committed", actor="tapdb_operator"
    )
    assert outcome["phase"] == "committed"
    with engine.begin() as connection:
        after = capture(connection, target)
        assert verify_sequence_floors(after, floors=floors)["ok"]
        assert (
            connection.execute(
                text(f"SELECT nextval('\"{target['schema_name']}\".objects_uid_seq')")
            ).scalar_one()
            == 11
        )
    chain = verify_receipt_chain(read_receipts(tmp_path), head=read_head(tmp_path))
    assert chain.ok and chain.count == 3


def test_rollback_keeps_external_floors_and_refuses_same_plan_retry(
    allocator, tmp_path
):
    engine, target = allocator
    with engine.connect() as connection:
        transaction = connection.begin()
        before = capture(connection, target)
        plan = build_sequence_advance_plan(
            before,
            floors=[{"name": "objects_uid_seq", "value": 20, "source": "reservation"}],
        )
        pending = apply_sequence_advance_plan(
            connection, plan, writer_fence=fence(before), receipts_dir=tmp_path
        )
        transaction.rollback()
    with engine.begin() as connection:
        assert capture(connection, target) == before
        with pytest.raises(SequenceProtectionError, match="already attempted"):
            apply_sequence_advance_plan(
                connection, plan, writer_fence=fence(before), receipts_dir=tmp_path
            )
    assert read_receipts(tmp_path)[0].detail["floors"][-1]["value"] == 23
    with engine.begin() as connection:
        current = capture(connection, target)
        insufficient = build_sequence_advance_plan(current, floors=[])
        with pytest.raises(SequenceProtectionError, match="previous attempt"):
            apply_sequence_advance_plan(
                connection,
                insufficient,
                writer_fence=fence(current),
                receipts_dir=tmp_path,
            )
    with engine.begin() as connection:
        current = capture(connection, target)
        retained = read_receipts(tmp_path)[0].detail["floors"]
        recovery = build_sequence_advance_plan(current, floors=retained)
        with pytest.raises(SequenceProtectionError, match="Unresolved prior allocator"):
            apply_sequence_advance_plan(
                connection, recovery, writer_fence=fence(current), receipts_dir=tmp_path
            )
        record_sequence_advance_outcome(
            pending, receipts_dir=tmp_path, outcome="ambiguous", actor="tapdb_operator"
        )
        with pytest.raises(SequenceProtectionError, match="Unresolved prior allocator"):
            apply_sequence_advance_plan(
                connection, recovery, writer_fence=fence(current), receipts_dir=tmp_path
            )
        # The retained caller observed rollback; a new process cannot invent this.
        record_sequence_advance_outcome(
            pending,
            receipts_dir=tmp_path,
            outcome="rolled_back",
            actor="tapdb_operator",
        )
        applied = apply_sequence_advance_plan(
            connection, recovery, writer_fence=fence(current), receipts_dir=tmp_path
        )
        assert sequence_next_value(applied["inventory"]["sequences"][0]) == 26


def test_rolled_back_nextval_is_not_reclaimed(allocator):
    engine, target = allocator
    with engine.connect() as connection:
        transaction = connection.begin()
        allocated = connection.execute(
            text(f"SELECT nextval('\"{target['schema_name']}\".objects_uid_seq')")
        ).scalar_one()
        transaction.rollback()
    with engine.begin() as connection:
        plan = build_sequence_advance_plan(capture(connection, target), floors=[])
    assert allocated == 8 and plan["advances"][0]["next_value"] == 11


def test_cached_old_sessions_block_advance_until_closed(allocator, tmp_path):
    engine, target = allocator
    schema = target["schema_name"]
    with engine.begin() as connection:
        connection.execute(text(f'ALTER SEQUENCE "{schema}".objects_uid_seq CACHE 4'))
    other = engine.connect()
    assert (
        other.execute(
            text(f"SELECT nextval('\"{schema}\".objects_uid_seq')")
        ).scalar_one()
        == 8
    )
    other.commit()
    with engine.begin() as connection:
        before = capture(connection, target)
        assert before["sequences"][0]["last_value"] == 17
        with pytest.raises(SequenceProtectionError, match="sessions"):
            apply_sequence_advance_plan(
                connection,
                build_sequence_advance_plan(before, floors=[]),
                writer_fence=fence(before),
                receipts_dir=tmp_path,
            )
    other.close()
    with engine.begin() as connection:
        before = capture(connection, target)
        result = apply_sequence_advance_plan(
            connection,
            build_sequence_advance_plan(before, floors=[]),
            writer_fence=fence(before),
            receipts_dir=tmp_path,
        )
        assert sequence_next_value(result["inventory"]["sequences"][0]) == 20


def test_mutation_rejects_unfenced_login_and_false_attestation(
    allocator, pg_instance, tmp_path
):
    engine, target = allocator
    with engine.begin() as connection:
        connection.execute(
            text(
                f'GRANT CONNECT ON DATABASE "{target["database"]}" TO "{pg_instance["user"]}"'
            )
        )
    with engine.begin() as connection:
        current = capture(connection, target)
        with pytest.raises(SequenceProtectionError, match="CONNECT"):
            validate_writer_fence(connection, current, fence(current))
        with pytest.raises(SequenceProtectionError, match="required"):
            apply_sequence_advance_plan(
                connection,
                build_sequence_advance_plan(current, floors=[]),
                writer_fence={"fenced": True},
                receipts_dir=tmp_path,
            )
        disabled = {
            "mode": "database_connections_disabled",
            "database_oid": current["physical_target"]["database_oid"],
            "connection_backend": backend_identity(connection),
            "provider_contract": None,
        }
        with pytest.raises(SequenceProtectionError, match="not disabled"):
            validate_writer_fence(connection, current, disabled)


def test_missing_unused_and_unknown_generators_fail_closed(allocator):
    engine, target = allocator
    schema = target["schema_name"]
    with engine.begin() as connection:
        connection.execute(text(f'CREATE SEQUENCE "{schema}".abc_instance_seq'))
        unknown = capture(connection, target)
        assert unknown["sequences"][0]["mapping"]["kind"] == "unmapped"
        with pytest.raises(SequenceProtectionError, match="Unknown"):
            build_sequence_advance_plan(unknown, floors=[])
        bound_target = dict(
            target,
            sequence_mappings={
                "abc_instance_seq": {
                    "kind": "prefix",
                    "prefix": "ABC",
                    "evidence": "explicit local test CREATE SEQUENCE definition",
                }
            },
        )
        bound = capture(connection, bound_target)
        assert bound["sequences"][0]["is_called"] is False
        assert (
            build_sequence_advance_plan(bound, floors=[])["advances"][0]["next_value"]
            == 1
        )
        connection.execute(text(f'DROP SEQUENCE "{schema}".abc_instance_seq'))
        with pytest.raises(SequenceProtectionError, match="missing"):
            capture(connection, bound_target)


def test_stale_target_or_inventory_cannot_apply(allocator, tmp_path):
    engine, target = allocator
    with engine.begin() as connection:
        current = capture(connection, target)
        plan = build_sequence_advance_plan(current, floors=[])
        connection.execute(
            text(f"SELECT nextval('\"{target['schema_name']}\".objects_uid_seq')")
        )
        with pytest.raises(SequenceProtectionError, match="Stale"):
            apply_sequence_advance_plan(
                connection, plan, writer_fence=fence(current), receipts_dir=tmp_path
            )
        tampered = dict(plan, target=dict(target, database="different_database"))
        with pytest.raises(IdentityInventoryError, match="checksum"):
            apply_sequence_advance_plan(
                connection, tampered, writer_fence=fence(current), receipts_dir=tmp_path
            )
        with pytest.raises(SequenceProtectionError, match="inconsistent"):
            apply_sequence_advance_plan(
                connection,
                seal_receipt(tampered),
                writer_fence=fence(current),
                receipts_dir=tmp_path,
            )


def test_noop_plan_does_not_change_called_state(allocator, tmp_path):
    engine, target = allocator
    with engine.begin() as connection:
        before = capture(connection, target)
        result = apply_sequence_advance_plan(
            connection,
            build_sequence_advance_plan(before, floors=[]),
            writer_fence=fence(before),
            receipts_dir=tmp_path,
        )
        assert result["inventory"] == before


def test_broken_receipt_chain_and_nonabsolute_storage_block_mutation(
    allocator, tmp_path
):
    engine, target = allocator
    with engine.begin() as connection:
        current = capture(connection, target)
        plan = build_sequence_advance_plan(current, floors=[])
        with pytest.raises(SequenceProtectionError, match="absolute"):
            apply_sequence_advance_plan(
                connection,
                plan,
                writer_fence=fence(current),
                receipts_dir=Path("relative"),
            )


def test_strong_gate_lifecycle_retains_session_through_verified_commit(
    allocator, control_connection, tmp_path
):
    from daylily_tapdb.sequences import (
        acquire_database_writer_fence,
        release_database_writer_fence,
    )

    engine, target = allocator
    extra_admin = "fixture_admin_" + uuid4().hex
    with engine.connect() as connection:
        with connection.begin():
            connection.execute(text(f'CREATE ROLE "{extra_admin}" LOGIN SUPERUSER'))
            current = capture(connection, target)
            with pytest.raises(SequenceProtectionError, match="CONNECT"):
                validate_writer_fence(connection, current, fence(current))
            plan = build_sequence_advance_plan(
                current,
                floors=[{"name": "objects_uid_seq", "value": 9, "source": "original"}],
            )
        try:
            with pytest.raises(SequenceProtectionError, match="unknown privileged"):
                acquire_database_writer_fence(
                    connection,
                    control_connection=control_connection,
                    inventory=current,
                    receipts_dir=tmp_path,
                )
        finally:
            with connection.begin():
                connection.execute(text(f'DROP ROLE "{extra_admin}"'))
        acquired = acquire_database_writer_fence(
            connection,
            control_connection=control_connection,
            inventory=current,
            receipts_dir=tmp_path,
        )
        try:
            with connection.begin():
                assert (
                    connection.execute(
                        text(
                            "SELECT datallowconn FROM pg_database WHERE datname=current_database()"
                        )
                    ).scalar_one()
                    is False
                )
                applied = apply_sequence_advance_plan(
                    connection,
                    plan,
                    writer_fence=acquired["fence"],
                    receipts_dir=tmp_path,
                )
            committed = record_sequence_advance_outcome(
                applied,
                receipts_dir=tmp_path,
                outcome="committed",
                actor="tapdb_operator",
            )
            released = release_database_writer_fence(
                connection,
                acquired,
                result=committed,
                receipts_dir=tmp_path,
                control_connection=control_connection,
            )
            assert released["phase"] == "released"
            assert released["fence_sha256"] == acquired["sha256"]
        finally:
            with connection.begin():
                connection.execute(
                    text(
                        f'ALTER DATABASE "{target["database"]}" ALLOW_CONNECTIONS true'
                    )
                )
    receipts = read_receipts(tmp_path)
    assert verify_receipt_chain(receipts, head=read_head(tmp_path)).ok
    assert [item.detail["phase"] for item in receipts] == [
        "acquire_intent",
        "acquired",
        "intent",
        "applied_pending_commit",
        "committed",
        "release_intent",
        "released",
    ]


def test_strong_gate_failed_acquisition_never_reopens_and_cannot_be_retried_blindly(
    allocator, control_connection, tmp_path
):
    from daylily_tapdb.sequences import acquire_database_writer_fence

    engine, target = allocator
    other = engine.connect()
    other.execute(text("SELECT 1"))
    other.commit()
    with engine.connect() as connection:
        with connection.begin():
            current = capture(connection, target)
        try:
            with pytest.raises(SequenceProtectionError, match="sessions"):
                acquire_database_writer_fence(
                    connection,
                    control_connection=control_connection,
                    inventory=current,
                    receipts_dir=tmp_path,
                )
            with connection.begin():
                assert (
                    connection.execute(
                        text(
                            "SELECT datallowconn FROM pg_database WHERE datname=current_database()"
                        )
                    ).scalar_one()
                    is False
                )
            other.close()
            # Explicit fixture recovery reopens; it does not erase unresolved evidence.
            with connection.begin():
                connection.execute(
                    text(
                        f'ALTER DATABASE "{target["database"]}" ALLOW_CONNECTIONS true'
                    )
                )
            with pytest.raises(SequenceProtectionError, match="unresolved"):
                acquire_database_writer_fence(
                    connection,
                    control_connection=control_connection,
                    inventory=current,
                    receipts_dir=tmp_path,
                )
        finally:
            other.close()
            with connection.begin():
                connection.execute(
                    text(
                        f'ALTER DATABASE "{target["database"]}" ALLOW_CONNECTIONS true'
                    )
                )
    receipts = read_receipts(tmp_path)
    assert receipts[-1].detail["phase"] == "acquire_intent"


def test_strong_gate_rejects_active_transaction_same_control_and_stale_inventory(
    allocator, control_connection, tmp_path
):
    from daylily_tapdb.sequences import acquire_database_writer_fence

    engine, target = allocator
    with engine.connect() as connection:
        with connection.begin():
            current = capture(connection, target)
            with pytest.raises(SequenceProtectionError, match="active"):
                acquire_database_writer_fence(
                    connection,
                    control_connection=control_connection,
                    inventory=current,
                    receipts_dir=tmp_path,
                )
        with pytest.raises(SequenceProtectionError, match="different control"):
            acquire_database_writer_fence(
                connection,
                control_connection=connection,
                inventory=current,
                receipts_dir=tmp_path,
            )
        with connection.begin():
            connection.execute(
                text(f"SELECT nextval('\"{target['schema_name']}\".objects_uid_seq')")
            )
        with pytest.raises(SequenceProtectionError, match="no longer matches"):
            acquire_database_writer_fence(
                connection,
                control_connection=control_connection,
                inventory=current,
                receipts_dir=tmp_path,
            )
        with connection.begin():
            assert (
                connection.execute(
                    text(
                        "SELECT datallowconn FROM pg_database WHERE datname=current_database()"
                    )
                ).scalar_one()
                is True
            )
    assert read_receipts(tmp_path) == []


def test_strong_gate_release_rejects_uncommitted_wrong_target_session_and_drift(
    allocator, control_connection, tmp_path
):
    from daylily_tapdb.sequences import (
        acquire_database_writer_fence,
        release_database_writer_fence,
    )

    engine, target = allocator
    with engine.connect() as connection:
        with connection.begin():
            current = capture(connection, target)
        acquired = acquire_database_writer_fence(
            connection,
            control_connection=control_connection,
            inventory=current,
            receipts_dir=tmp_path,
        )
        try:
            with connection.begin():
                applied = apply_sequence_advance_plan(
                    connection,
                    build_sequence_advance_plan(current, floors=[]),
                    writer_fence=acquired["fence"],
                    receipts_dir=tmp_path,
                )
                with pytest.raises(SequenceProtectionError, match="transaction"):
                    release_database_writer_fence(
                        connection,
                        acquired,
                        result=applied,
                        receipts_dir=tmp_path,
                        control_connection=control_connection,
                    )
            with pytest.raises(SequenceProtectionError, match="committed"):
                release_database_writer_fence(
                    connection,
                    acquired,
                    result=applied,
                    receipts_dir=tmp_path,
                    control_connection=control_connection,
                )
            committed = record_sequence_advance_outcome(
                applied,
                receipts_dir=tmp_path,
                outcome="committed",
                actor="tapdb_operator",
            )
            wrong_target = seal_receipt(
                dict(
                    acquired, target=dict(acquired["target"], database="other_database")
                )
            )
            with pytest.raises(SequenceProtectionError, match="different fenced"):
                release_database_writer_fence(
                    connection,
                    wrong_target,
                    result=committed,
                    receipts_dir=tmp_path,
                    control_connection=control_connection,
                )
            wrong_pid = seal_receipt(dict(acquired, connection_pid=-1))
            with pytest.raises(SequenceProtectionError, match="retained"):
                release_database_writer_fence(
                    connection,
                    wrong_pid,
                    result=committed,
                    receipts_dir=tmp_path,
                    control_connection=control_connection,
                )
            with connection.begin():
                connection.execute(
                    text(
                        f"SELECT nextval('\"{target['schema_name']}\".objects_uid_seq')"
                    )
                )
            with pytest.raises(SequenceProtectionError, match="not confirmed"):
                release_database_writer_fence(
                    connection,
                    acquired,
                    result=committed,
                    receipts_dir=tmp_path,
                    control_connection=control_connection,
                )
            with connection.begin():
                assert (
                    connection.execute(
                        text(
                            "SELECT datallowconn FROM pg_database WHERE datname=current_database()"
                        )
                    ).scalar_one()
                    is False
                )
        finally:
            # Explicit isolated-fixture cleanup is not a library release fallback.
            with connection.begin():
                connection.execute(
                    text(
                        f'ALTER DATABASE "{target["database"]}" ALLOW_CONNECTIONS true'
                    )
                )


def test_strong_gate_release_error_retains_closed_gate_and_failed_receipt(
    allocator, control_connection, tmp_path
):
    from sqlalchemy import event

    from daylily_tapdb.sequences import (
        acquire_database_writer_fence,
        release_database_writer_fence,
    )

    engine, target = allocator
    with engine.connect() as connection:
        with connection.begin():
            current = capture(connection, target)
        acquired = acquire_database_writer_fence(
            connection,
            control_connection=control_connection,
            inventory=current,
            receipts_dir=tmp_path,
        )

        def refuse_release(conn, cursor, statement, parameters, context, executemany):
            if (
                statement.startswith("ALTER DATABASE")
                and "ALLOW_CONNECTIONS true" in statement
            ):
                raise RuntimeError("simulated connection failure before gate release")

        try:
            with connection.begin():
                applied = apply_sequence_advance_plan(
                    connection,
                    build_sequence_advance_plan(current, floors=[]),
                    writer_fence=acquired["fence"],
                    receipts_dir=tmp_path,
                )
            committed = record_sequence_advance_outcome(
                applied,
                receipts_dir=tmp_path,
                outcome="committed",
                actor="tapdb_operator",
            )
            event.listen(control_connection, "before_cursor_execute", refuse_release)
            with pytest.raises(RuntimeError, match="simulated"):
                release_database_writer_fence(
                    connection,
                    acquired,
                    result=committed,
                    receipts_dir=tmp_path,
                    control_connection=control_connection,
                )
            event.remove(control_connection, "before_cursor_execute", refuse_release)
            with connection.begin():
                assert (
                    connection.execute(
                        text(
                            "SELECT datallowconn FROM pg_database WHERE datname=current_database()"
                        )
                    ).scalar_one()
                    is False
                )
            assert read_receipts(tmp_path)[-1].detail["phase"] == "release_intent"
        finally:
            if event.contains(
                control_connection, "before_cursor_execute", refuse_release
            ):
                event.remove(
                    control_connection, "before_cursor_execute", refuse_release
                )
            with connection.begin():
                connection.execute(
                    text(
                        f'ALTER DATABASE "{target["database"]}" ALLOW_CONNECTIONS true'
                    )
                )


def test_failed_postadvance_check_rolls_back_savepoint_and_retains_intent(
    allocator, tmp_path, monkeypatch
):
    import daylily_tapdb.sequences as sequence_module

    engine, target = allocator
    with engine.begin() as connection:
        current = capture(connection, target)
        plan = build_sequence_advance_plan(
            current,
            floors=[{"name": "objects_uid_seq", "value": 11, "source": "source"}],
        )
        monkeypatch.setattr(
            sequence_module,
            "verify_sequence_floors",
            lambda *args, **kwargs: {"ok": False},
        )
        with pytest.raises(SequenceProtectionError, match="Post-advance"):
            apply_sequence_advance_plan(
                connection, plan, writer_fence=fence(current), receipts_dir=tmp_path
            )
        assert capture(connection, target) == current
    receipts = read_receipts(tmp_path)
    assert [item.status for item in receipts] == ["intent", "failed"]
    assert receipts[1].detail["floors"][-1]["value"] == 14


def test_stored_deleted_prefix_and_template_binding_remain_distinct(allocator):
    engine, target = allocator
    schema = target["schema_name"]
    with engine.begin() as connection:
        connection.execute(
            text(
                f'CREATE SEQUENCE "{schema}".abc_instance_seq START 2 INCREMENT 3 MINVALUE 2'
            )
        )
        connection.execute(text(f'CREATE SEQUENCE "{schema}".xyz_instance_seq'))
        connection.execute(
            text(
                f'CREATE TABLE "{schema}".reservations(euid_prefix text, euid_seq bigint, is_deleted bool)'
            )
        )
        connection.execute(
            text(
                f"INSERT INTO \"{schema}\".reservations VALUES ('ABC',nextval('\"{schema}\".abc_instance_seq'),true)"
            )
        )
        connection.execute(
            text(f'CREATE TABLE "{schema}".generic_template(instance_prefix text)')
        )
        connection.execute(
            text(f"INSERT INTO \"{schema}\".generic_template VALUES ('XYZ')")
        )
        connection.execute(
            text(f'CREATE TABLE "{schema}".tapdb_identity_prefix_config(prefix text)')
        )
        connection.execute(
            text(
                f"INSERT INTO \"{schema}\".tapdb_identity_prefix_config VALUES ('ABC')"
            )
        )
        captured = capture(connection, target)
        states = {state["name"]: state for state in captured["sequences"]}
        assert states["abc_instance_seq"]["assigned_floor"] == 2
        assert states["abc_instance_seq"]["mapping"]["prefix"] == "ABC"
        assert states["xyz_instance_seq"]["mapping"]["prefix"] == "XYZ"
        assert states["xyz_instance_seq"]["assigned_floor"] is None
        connection.execute(text(f'DROP SEQUENCE "{schema}".xyz_instance_seq'))
        missing = capture(connection, target)
        assert missing["missing_generators"] == ["xyz_instance_seq"]
        with pytest.raises(SequenceProtectionError, match="Missing"):
            build_sequence_advance_plan(missing, floors=[])


@pytest.mark.parametrize(
    "declarations",
    [
        [],
        {"absent": {"kind": "prefix", "prefix": "ABC", "evidence": "explicit"}},
        {"abc_instance_seq": {"kind": "prefix", "prefix": "ABC"}},
        {
            "abc_instance_seq": {
                "kind": "prefix",
                "prefix": "XYZ",
                "evidence": "explicit",
            }
        },
        {
            "abc_instance_seq": {
                "kind": "prefix",
                "prefix": "invalid",
                "evidence": "explicit",
            }
        },
    ],
)
def test_unverified_or_wrong_prefix_mapping_declarations_rejected(
    allocator, declarations
):
    engine, target = allocator
    with engine.begin() as connection:
        connection.execute(
            text(f'CREATE SEQUENCE "{target["schema_name"]}".abc_instance_seq')
        )
        with pytest.raises(SequenceProtectionError):
            capture(connection, dict(target, sequence_mappings=declarations))


def test_incomplete_prefix_column_pair_rejected(allocator):
    engine, target = allocator
    with engine.begin() as connection:
        connection.execute(
            text(f'CREATE TABLE "{target["schema_name"]}".broken(euid_prefix text)')
        )
        with pytest.raises(SequenceProtectionError, match="Incomplete"):
            capture(connection, target)
