-- 20260303_120010_add_outbox_event.sql
--
-- Add a minimal Postgres transactional outbox for durable cross-service events.

CREATE TABLE IF NOT EXISTS outbox_event (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_id UUID NOT NULL,
    tenant_id UUID,
    event_type TEXT NOT NULL,
    aggregate_euid TEXT,
    payload JSONB NOT NULL,
    destination TEXT NOT NULL,
    dedupe_key TEXT NOT NULL,
    status TEXT NOT NULL DEFAULT 'pending'
        CHECK (status IN ('pending', 'delivering', 'delivered', 'failed')),
    attempt_count INT NOT NULL DEFAULT 0,
    next_attempt_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    last_error TEXT,
    created_dt TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    delivered_dt TIMESTAMP WITH TIME ZONE,

    CONSTRAINT unique_outbox_event_destination_dedupe_key UNIQUE (destination, dedupe_key)
);

CREATE INDEX IF NOT EXISTS idx_outbox_event_status_next_attempt_at
    ON outbox_event(status, next_attempt_at);
CREATE INDEX IF NOT EXISTS idx_outbox_event_tenant_created_dt
    ON outbox_event(tenant_id, created_dt DESC);

