-- Apply the canonical forced-RLS and audit-attribution asset on upgrades.
-- tapdb-allow-schema: generic_template
-- tapdb-allow-schema: generic_instance
-- tapdb-allow-schema: generic_instance_lineage
-- tapdb-allow-schema: audit_log
-- tapdb-allow-schema: outbox_event
-- tapdb-allow-schema: outbox_event_attempt
-- tapdb-allow-schema: inbox_message
-- tapdb-allow-schema: tapdb_identity_prefix_config
-- tapdb-allow-schema: tapdb_legacy_outbox_mapping
-- tapdb-allow-schema: tapdb_runtime_principal_scope
-- tapdb-allow-new-table: tapdb_runtime_principal_scope
-- Identity columns, EUID assignments, sequence state, relationships, and
-- provenance timestamps are unchanged. The only data transformation is:
-- audit_log.changed_by NULL/empty -> migration:pre-9.2-unattributed.
-- tapdb-allow-column: audit_log.changed_by
-- tapdb-transformation: audit_log.changed_by:null_or_empty_to_pre92_unattributed_v1
-- tapdb-include: ../rls.sql
